# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Flags',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='MapArray',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='Mines',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='UnderArray',
            field=models.TextField(),
        ),
    ]
