# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0003_game_maplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Score', models.IntegerField()),
            ],
        ),
    ]
